#!/bin/sh

#Brain.Fm
#Se over bokmerker?

#If you have the optional dependencies iconutil, Imagemagick convert, and
#Imagemagick identify in your PATH, Nativefier will automatically convert the
#.png to a .icns for you.

# https://github.com/jiahaog/nativefier-icons
# https://github.com/jiahaog/nativefier/blob/master/docs/api.md

mkdir tmp/
nativefier --name "The Lounge" --icon icons/thelounge.png --counter --bounce --title-bar-style hidden --single-instance https://chat.fuzzy76.net/ tmp/
nativefier --name "Do nothing for 2 minutes" --icon icons/calm.png --fast-quit --full-screen --hide-window-frame --title-bar-style hidden --disable-context-menu --single-instance http://www.donothingfor2minutes.com tmp/
nativefier --name "Brain.fm" --icon icons/brainfm.png --single-instance https://www.brain.fm/ tmp/
nativefier --name "Jira Utdanning.no" --counter --bounce --single-instance 'https://kompetansenorge.atlassian.net/jira/' tmp/
