#!/bin/sh

#nativefier --name "Microsoft Planner" https://tasks.office.com/
#The Lounge
#Brain.Fm
#Se over bokmerker?

#If you have the optional dependencies iconutil, Imagemagick convert, and
#Imagemagick identify in your PATH, Nativefier will automatically convert the
#.png to a .icns for you.

#https://github.com/jiahaog/nativefier-icons

nativefier --name "The Lounge" --icon icons/thelounge.png --counter --bounce --title-bar-style hidden --single-instance  https://matilda.fuzzy76.net:9000/