#!/bin/sh

#Brain.Fm
#Se over bokmerker?

#If you have the optional dependencies iconutil, Imagemagick convert, and
#Imagemagick identify in your PATH, Nativefier will automatically convert the
#.png to a .icns for you.

#https://github.com/jiahaog/nativefier-icons

mkdir tmp/
nativefier --name "The Lounge" --icon icons/thelounge.png --counter --bounce --title-bar-style hidden --single-instance  
https://matilda.fuzzy76.net:9000/ tmp/
nativefier --name "Microsoft Planner" --icon icons/msplanner.png --single-instance https://tasks.office.com/ tmp/
